name: Test Terraform Action
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  invalid-terraform:
    name: Validate Invalid Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Invalid Terraform Formatting
        id: invalid-terraform
        uses: ./
        continue-on-error: true
        with:
          working_directory: './tf-tests/invalidly-formatted'
          tflint_version: 'latest'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: nick-fields/assert-action@v2
        with:
          expected: success
          actual: ${{ steps.invalid-terraform.outcome }}
          comparison: notEqual

  valid-terraform:
    name: Validate Valid Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Valid Terraform Formatting
        uses: ./
        id: valid-terraform
        continue-on-error: true
        with:
          working_directory: './tf-tests/validly-formatted'
          tflint_version: 'latest'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: nick-fields/assert-action@v2
        with:
          expected: success
          actual: ${{ steps.valid-terraform.outcome }}
          comparison: exact
  create-release-tag:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Create Release Tag
    runs-on: ubuntu-latest
    needs: [valid-terraform, invalid-terraform]
    permissions:
      contents: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GH_PAT: op://Home_Lab/GitHub-Actions-PAT/credential
      - uses: phish108/autotag-action@v1.1.64
        id: autotag
        with:
          github-token: ${{ env.GH_PAT }}
          with-v: "true"
  check-failure:
    name: Check Failure
    runs-on: ubuntu-latest
    needs: [valid-terraform, invalid-terraform, create-release-tag]
    if: failure()
    steps:
      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DISCORD_WEBHOOK: op://Home_Lab/Discord-Webhooks/github-actions-bot-error
      - name: Discord notification
        uses: Ilshidur/action-discord@master
        with:
          args: |
            {{ EVENT_PAYLOAD.repository.full_name }} has encountered an error.
            Github Workflow Run URL: ${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}
            Github Ref : ${{github.ref}}
